apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute-public.yaml
  - httproute-redirect.yaml
  - analytics-route.yaml

configMapGenerator:
  - name: froystein-jp-analytics-config
    namespace: froystein-jp
    files:
      - analytics-config.js

labels:
  - pairs:
      app.kubernetes.io/part-of: froystein-jp
    includeSelectors: false

images:
  - name: ghcr.io/stianfro/froystein.jp
    newTag: latest
